name: Build & release
on:
  push:
    tags: [v**]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: src/dist/windows/1cv8_postgres_helper.exe
