name: Build & release
on:
  push:
    tags: [v**]
    branches: ['*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
      - name: Check file existence
        uses: andstor/file-existence-action@v3
        with:
          files: src/dist/windows/1cv8_postgres_helper.exe
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/dist/windows/1cv8_postgres_helper.exe
